development:
  adapter: postgresql
  database: myrecipes_development
  username: postgres
  password: <%= Rails.application.credentials.pg[:db_password] %>
  host: localhost
  prepared_statements: false

test:
  adapter: postgresql
  database: myrecipes_test
  username: postgres
  password: <%= Rails.application.credentials.pg[:db_password] %>
  host: localhost
  prepared_statements: false